# Generated by Django 4.2.4 on 2024-06-10 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('no_media', 'Без медиа'), ('photo', 'Фото'), ('video', 'Видео'), ('document', 'Документ')], help_text='Тип медиа', max_length=50, verbose_name='Тип медиа')),
                ('text', models.TextField(blank=True, help_text='Текст рассылки', max_length=4096, null=True, verbose_name='Текст')),
                ('file', models.FileField(blank=True, help_text='Файл для рассылки', null=True, upload_to='files_mailing', verbose_name='Файл')),
                ('date_malling', models.DateTimeField(help_text='Дата рассылки', verbose_name='Дата')),
                ('is_sent', models.BooleanField(default=False, help_text='Статус отправки', verbose_name='Статус отправки')),
            ],
            options={
                'verbose_name': 'Рассылки',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID пользователя в Telegram')),
                ('username', models.CharField(default=None, max_length=255, null=True, verbose_name='Имя пользователя')),
                ('full_name', models.CharField(default=None, max_length=255, null=True, verbose_name='Полное имя пользователя')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='Ссылка на пользователя')),
                ('phone_number', models.CharField(blank=True, default=None, max_length=12, null=True, verbose_name='Номер телефона')),
                ('bot_unblocked', models.BooleanField(default=True, verbose_name='Бот разблокирован пользователем')),
                ('is_unblocked', models.BooleanField(default=True, verbose_name='Пользователь разблокирован')),
            ],
            options={
                'verbose_name': 'Пользователя',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Текст кнопки')),
                ('link', models.CharField(max_length=1024, verbose_name='Ссылка')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='telegram.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Кнопку для рассылки',
                'verbose_name_plural': 'Кнопки для рассылки',
            },
        ),
    ]
