# Generated by Django 4.2.4 on 2024-06-11 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('no_media', 'Без медиа'), ('photo', 'Фото'), ('video', 'Видео'), ('document', 'Документ')], help_text='Тип медиа', max_length=50, verbose_name='Тип медиа')),
                ('text', models.TextField(blank=True, help_text='Текст рассылки', max_length=4096, null=True, verbose_name='Текст')),
                ('file', models.FileField(blank=True, help_text='Файл для рассылки', null=True, upload_to='files_mailing', verbose_name='Файл')),
                ('date_malling', models.DateTimeField(help_text='Дата рассылки', verbose_name='Дата')),
                ('is_sent', models.BooleanField(default=False, help_text='Статус отправки', verbose_name='Статус отправки')),
            ],
            options={
                'verbose_name': 'Рассылки',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='TgUserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='TradingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес точки')),
                ('title', models.CharField(max_length=80, verbose_name='Название точки')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Торговую точку',
                'verbose_name_plural': 'Торговые точки',
            },
        ),
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID пользователя в Telegram')),
                ('username', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Никнейм')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=12, unique=True, verbose_name='Номер телефона')),
                ('passport_photo', models.ImageField(blank=True, default=None, null=True, upload_to='user_data/', verbose_name='Фото паспорта')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('bot_unblocked', models.BooleanField(default=True, verbose_name='Бот разблокирован пользователем')),
                ('is_unblocked', models.BooleanField(default=True, verbose_name='Пользователь разблокирован')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='telegram.tgusercategory', verbose_name='Категория пользователя')),
            ],
            options={
                'verbose_name': 'Пользователя',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Текст кнопки')),
                ('link', models.CharField(max_length=1024, verbose_name='Ссылка')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buttons', to='telegram.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Кнопку для рассылки',
                'verbose_name_plural': 'Кнопки для рассылки',
            },
        ),
    ]
