# Generated by Django 4.2.4 on 2024-06-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='tgusercategory',
            name='title',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название категории'),
        ),
    ]
